# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'NotaryJessy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotaryJessy
    pod 'AFNetworking'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'IQKeyboardManager', '4.0.13'

  target 'NotaryJessyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotaryJessyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
